<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/responsive.bootstrap4.js') }}"></script>
<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/datatables.checkboxes.min.js') }}"></script>
<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/datatables.buttons.min.js') }}"></script>
{{-- <script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/jszip.min.js') }}"></script>
<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/pdfmake.min.js') }}"></script>
<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/vfs_fonts.js') }}"></script> --}}
<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/buttons.html5.min.js') }}"></script>
<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/buttons.print.min.js') }}"></script>
<script src="{{ asset('backadmin/theme/vendors/js/tables/datatable/dataTables.rowGroup.min.js') }}"></script>
<script src="{{ asset('backadmin/app/js/datatable.lang.id.js') }}"></script>